cmake_minimum_required(VERSION 3.10)

project(PentaGame)
# Force function/data section separation and garbage collection
if(NOT MSVC)
    add_compile_options(
        -ffunction-sections 
        -fdata-sections
        -fno-unwind-tables 
        -fno-asynchronous-unwind-tables
    )
    add_link_options(
        -Wl,--gc-sections
    )
    # If using Clang on macOS, use -Wl,-dead_strip instead:
    if(APPLE)
        remove_link_options(-Wl,--gc-sections)
        add_link_options(-Wl,-dead_strip)
    endif()
endif()
# 1. Turn on raylib's custom build switcher before adding the subdirectory
set(CUSTOMIZE_BUILD ON CACHE BOOL "" FORCE)

set(SUPPORT_TRACELOG OFF CACHE BOOL "" FORCE)
set(SUPPORT_GESTURES_SYSTEM OFF CACHE BOOL "" FORCE)
set(SUPPORT_RPRAND_GENERATOR OFF CACHE BOOL "" FORCE)
set(SUPPORT_MOUSE_GESTURES OFF CACHE BOOL "" FORCE)
set(SUPPORT_SSH_KEYBOARD_RPI OFF CACHE BOOL "" FORCE)
set(SUPPORT_BUSY_WAIT_LOOP OFF CACHE BOOL "" FORCE)
set(SUPPORT_WINMM_HIGHRES_TIMER OFF CACHE BOOL "" FORCE)
set(SUPPORT_PARTIALBUSY_WAIT_LOOP OFF CACHE BOOL "" FORCE)
set(SUPPORT_SCREEN_CAPTURE OFF CACHE BOOL "" FORCE)
set(SUPPORT_COMPRESSION_API OFF CACHE BOOL "" FORCE)
set(SUPPORT_AUTOMATION_EVENTS OFF CACHE BOOL "" FORCE)
set(SUPPORT_CUSTOM_FRAME_CONTROL OFF CACHE BOOL "" FORCE)
set(SUPPORT_CLIPBOARD_IMAGE OFF CACHE BOOL "" FORCE)
#camera
set(SUPPORT_CAMERA_SYSTEM OFF CACHE BOOL "" FORCE)
set(RCAMERA_IMPLEMENTATION OFF CACHE BOOL "" FORCE)
set(RCAMERA_STANDALONE OFF CACHE BOOL "" FORCE)
#shapes
set(SUPPORT_MODULE_RSHAPES ON CACHE BOOL "" FORCE)
set(SUPPORT_QUADS_DRAW_MODE OFF CACHE BOOL "" FORCE)
#images
set(SUPPORT_MODULE_RTEXTURES ON CACHE BOOL "" FORCE)
set(SUPPORT_IMAGE_EXPORT OFF CACHE BOOL "" FORCE)
set(SUPPORT_IMAGE_GENERATION OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_BMP OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_PNG OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_TGA OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_JPG OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_GIF OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_QOI OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_PSD OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_HDR OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_PIC OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_PNM OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_DDS OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_PKM OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_KTX OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_PVR OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_ASTC OFF CACHE BOOL "" FORCE)
#fonts
set(SUPPORT_MODULE_RTEXT ON CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_FNT OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_TTF OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_BDF OFF CACHE BOOL "" FORCE)
#models
set(SUPPORT_MODULE_RMODELS OFF CACHE BOOL "" FORCE)
set(SUPPORT_MESH_GENERATION OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_OBJ OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_MTL OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_IQM OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_GLTF OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_GLTF_WRITE OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_VOX OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_M3D OFF CACHE BOOL "" FORCE)
#audio
set(SUPPORT_MODULE_RAUDIO ON CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_WAV OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_OGG ON CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_MP3 OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_QOA OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_FLAC OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_XM OFF CACHE BOOL "" FORCE)
set(SUPPORT_FILEFORMAT_MOD OFF CACHE BOOL "" FORCE)

add_subdirectory(../../raylib ${CMAKE_CURRENT_BINARY_DIR}/raylib)

add_executable(${PROJECT_NAME} 
    src/main.c 
    src/rocketlaunch.h
    src/avalanche.h
    src/pathbreaker.h
)
target_link_libraries(${PROJECT_NAME}  
    PRIVATE raylib 
) 
add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD COMMAND strip --strip-all $<TARGET_FILE:${PROJECT_NAME}>)
include(CheckIPOSupported)
check_ipo_supported(RESULT ipo_supported OUTPUT error)
if(ipo_supported)
    set_property(TARGET ${PROJECT_NAME} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
endif()
